comment_width = 80
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
version = "Two"
wrap_comments = true